spring:
  profiles:
    active: @env@

mybatis:
  type-aliases-package: com.k66.cxzt.model
  mapper-locations: classpath*:mapper/*.xml

server:
  servlet:
    context-path: /

leshui:
  url: https://open.leshui365.com
#  app-key: 3e05c9bba4314f0da1776b5ec90ca1bc
  app-key: 88148c453a314b6ba9f07550ada6ece4
#  app-secret: 2759250e-ac32-4f5f-83b7-dd7cedd85078
  app-secret: cfd07267-6e61-455e-a65e-39b848e145ec
