spring:
  profiles:
    active: @env@

mybatis:
  type-aliases-package: com.k66.cxzt.model
  mapper-locations: classpath*:mapper/*.xml

server:
  servlet:
    context-path: /

leshui:
  url: https://open.leshui365.com
  app-key: 3e05c9bba4314f0da1776b5ec90ca1bc
  app-secret: 2759250e-ac32-4f5f-83b7-dd7cedd85078
