spring:
  profiles:
    active: @env@

mybatis:
  type-aliases-package: com.k66.cxzt.model
  mapper-locations: classpath*:mapper/*.xml

server:
  servlet:
    context-path: /

leshui:
  url: https://open.leshui365.com
  app-key: 88148c453a314b6ba9f07550ada6ece4
  app-secret: cfd07267-6e61-455e-a65e-39b848e145ec
